### ISSUE TITLE
Rework configuration logic.

### ISSUE THREAD

**Issue by bunchc** [mrlesmithjr/packer-builder#4]
At the moment configuration logic is spread between different modules and `distro.yml`. I propose the following:

- Configuration details should be stored in `config/`
- Information used to populate the Packer build template to be moved to `config/distro.yml`
- Additional run time specific configuration to `config/config.yml`

An example of additional build specific details stored in `distros.yml`

```yaml
---
Alpine:
  builders:
    - qemu
    - virtualbox-iso
    - vmware-iso
  cpus: 1
  disk_adapter_type: scsi
  disk_size: 36864
  memory: 1024
  password: P@55w0rd
  username: root
  vagrant_box: true
  versions:
    3.8:
      iso_checksum: 20d20e0658b6cc361832cfb49367f0a4c33570ef1521f2e394e9164d2a9bd9df
      iso_checksum_type: sha256
      iso_url: http://dl-cdn.alpinelinux.org/alpine/v3.8/releases/x86_64/alpine-virt-3.8.4-x86_64.iso
    3.9:
      iso_checksum: 75a784aa16ab6311dbf597bdec86259183ba5e74633e7e9201300d848d457216
      iso_checksum_type: sha256
      iso_url: http://dl-cdn.alpinelinux.org/alpine/v3.9/releases/x86_64/alpine-virt-3.9.2-x86_64.iso
  provisioners:
    shell:
      type: shell
      scripts:
        - base.sh
        - virtualbox.sh
        - vmware.sh
        - cleanup.sh
        - vagrant.sh
        - zerodisk.sh
  post-processors:
    ovftool:
      type: shell-local
      inline: "ovftool lol//{{ user `vm_name` }}-{{ build_type }}-{{ timestamp }}/{{ user `vm_name` }}-{{ build_type }}-{{ timestamp }}.vmx lol//{{ user `vm_name` }}-{{ build_type }}-{{ timestamp }}/{{ user `vm_name` }}-{{ build_type }}-{{ timestamp }}.ovf"
      only:
        - vmware-iso
    vagrant:
      type: vagrant
      compression_level: "{{ user `compression_level` }}"
      keep_input_artifact: True
      output: "{{ user `vm_name` }}-{{ build_type }}-{{ timestamp }}.box"
    manifest:
      type: manifest
      strip_path: True
```

If extended to allow for "include: "conf/build.d/*"` style functionality this will allow for more granular control of the `distro.yml`
